server:
  port: ${PORT:8581}

spring:
  datasource:
    url: ${POSTGRES_URI:jdbc:postgresql://192.168.2.105:5435/evo_iam?currentSchema=evo_iam&useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true}
    username: ${POSTGRES_USER:evo_iam}
    password: ${POSTGRES_PASSWORD:Evotek@1234}
    hikari:
      maximum-pool-size: ${CONNECTION_POOL_SIZE:3}
  swagger:
    enabled: true
  redis:
    host: ${REDIS_HOST:192.168.2.105}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    embedded: false
    timeout: 10s
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USER:evotraininghrm@gmail.com}
    password: ${MAIL_PASSWORD:cubuxzweuajzyzwd}
    protocol: ${MAIL_PROTOCOL:smtp}
    properties.mail.smtp:
      auth: true
      starttls.enable: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_URI:http://localhost:8581/api/certificate/.well-known/jwks.json}
  ldap:
    embedded:
      base-dn: ${LDAP_BASE_DN:DC=evotek,DC=vn}
      port: ${LDAP_PORT:389}
      validation:
        enabled: false
    urls: ${LDAP_URLS:ldap://192.168.2.101:389}
    username: vlands
    password: 1qazXSW@
    prefix-mail: '@evotek.vn'
    filtered-group:
      enabled: ${LDAP_BASE_DN_GROUP_ENABLE:false}
      base-dn-group: ${LDAP_BASE_DN_GROUP:cn=users,dc=evotek,dc=vn}
      prefix: ${LDAP_BASE_DN_GROUP_PREFIX:evotek\}
      groups:
        - Evotek
    base: CN=Users,DC=evotek,DC=vn
    domain: evotek.vn
eureka:
  instance:
    nonSecurePort: ${server.port}
    secure-port-enabled: false
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8561}/eureka/
    config:
      default:
        loggerLevel: basic

security:
  authentication:
    jwt:
      access-token-expires-in: 30d

app:
  iam:
    domain: ${PUBLIC_DOMAIN:http://localhost:8081}
