ALTER TABLE TICKET.TICKET_FILE MODIFY FILE_TYPE VARCHAR2(20);
ALTER TABLE TICKET.TICKET_STATUS_HISTORY MODIFY STATUS VARCHAR2(20);
ALTER TABLE TICKET.TICKET MODIFY SERVICE_TYPE VARCHAR2(20);
ALTER TABLE TICKET.TICKET MODIFY STATUS VARCHAR2(20);

ALTER TABLE TICKET ADD NOTE_TEMP NVARCHAR2(1000);
UPDATE TICKET SET NOTE_TEMP = NOTE, NOTE = NULL;
ALTER TABLE TICKET DROP COLUMN NOTE;
ALTER TABLE TICKET RENAME COLUMN NOTE_TEMP TO NOTE;

ALTER TABLE TICKET ADD FEEDBACK_TEMP NVARCHAR2(1000);
UPDATE TICKET SET FEEDBACK_TEMP = FEEDBACK, FEEDBACK = NULL;
ALTER TABLE TICKET DROP COLUMN FEEDBACK;
ALTER TABLE TICKET RENAME COLUMN FEEDBACK_TEMP TO FEEDBACK;

ALTER TABLE TICKET ADD CONTENT_TEMP NVARCHAR2(2000);
UPDATE TICKET SET CONTENT_TEMP = CONTENT, CONTENT = NULL;
ALTER TABLE TICKET DROP COLUMN CONTENT;
ALTER TABLE TICKET RENAME COLUMN CONTENT_TEMP TO CONTENT;