-- --------------------------------------
-- Table structure for COMPLAINT_TEMPLATE
-- --------------------------------------
CREATE TABLE "TICKET"."COMPLAINT_TEMPLATE"
(
    "ID"                    VARCHAR2(36 CHAR) NOT NULL ENABLE,
    "BUILDING_ID"           VARCHAR2(36 CHAR) NOT NULL ENABLE,
    "FLOOR_ID"              VARCHAR2(36 CHAR) NOT NULL ENABLE,
    "CREATED_USER_ID"       VARCHAR2(36 CHAR) NOT NULL ENABLE,
    "NOTE"                  VARCHAR2(1000 CHAR),
    "STATUS"                VARCHAR2(20 CHAR) NOT NULL ENABLE,
    "TITLE"                 VARCHAR2(200 CHAR) NOT NULL ENABLE,
    "DELETED"               NUMBER(1,0) NOT NULL ENABLE,
    "CREATED_AT"            TIMESTAMP(6),
    "CREATED_BY"            VARCHAR2(50 CHAR) NOT NULL ENABLE,
    "LAST_MODIFIED_AT"      TIMESTAMP(6),
    "LAST_MODIFIED_BY"      VARCHAR2(50 CHAR),
    PRIMARY KEY ("ID");
);

CREATE
INDEX "TICKET"."COMPLAINT_TEMPLATE_DELETED_IDX" ON
"TICKET"."COMPLAINT_TEMPLATE" ("DELETED");

CREATE
INDEX "TICKET"."COMPLAINT_TEMPLATE_CREATED_USER_ID_IDX" ON
"TICKET"."COMPLAINT_TEMPLATE" ("CREATED_USER_ID");

CREATE
INDEX "TICKET"."COMPLAINT_TEMPLATE_BUILDING_ID_IDX" ON
"TICKET"."COMPLAINT_TEMPLATE" ("BUILDING_ID");

CREATE
INDEX "TICKET"."COMPLAINT_TEMPLATE_FLOOR_ID_IDX" ON
"TICKET"."COMPLAINT_TEMPLATE" ("FLOOR_ID");

-- -----------------------------------------------------
-- Table structure for COMPLAINT_TEMPLATE_UPDATE_HISTORY
-- -----------------------------------------------------
CREATE TABLE "TICKET"."COMPLAINT_TEMPLATE_UPDATE_HISTORY"
(
    "ID"                    VARCHAR2(36 CHAR) NOT NULL ENABLE,
    "COMPLAINT_TEMPLATE_ID" VARCHAR2(36 CHAR) NOT NULL ENABLE,
    "CREATED_USER_ID"       VARCHAR2(36 CHAR) NOT NULL ENABLE,
    "ACTION"                VARCHAR2(20 CHAR) NOT NULL ENABLE,
    "REASON"                VARCHAR2(1000 CHAR) NOT NULL ENABLE,
    "DELETED"               NUMBER(1,0) NOT NULL ENABLE,
    "CREATED_AT"            TIMESTAMP(6),
    "CREATED_BY"            VARCHAR2(50 CHAR) NOT NULL ENABLE,
    "LAST_MODIFIED_AT"      TIMESTAMP(6),
    "LAST_MODIFIED_BY"      VARCHAR2(50 CHAR),
    PRIMARY KEY ("ID");
);
