CREATE TABLE "TICKET"."COMPLAINT"
(
    "ID"                    VARCHAR2(36 CHAR) NOT NULL ENABLE,
    "BUILDING_ID"           VARCHAR2(36 CHAR) NOT NULL ENABLE,
    "CLOSED_AT"             TIMESTAMP(6),
    "CLOSED_USER_ID"        VARCHAR2(36 CHAR),
    "CONTENT"               VARCHAR2(2000 CHAR) NOT NULL ENABLE,
    "DELETED"               NUMBER(1,0) NOT NULL ENABLE,
    "FLOOR_ID"              VARCHAR2(36 CHAR) NOT NULL ENABLE,
    "RECEIVED_USER_ID"      VARCHAR2(36 CHAR),
    "STATUS"                VARCHAR2(20 CHAR),
    "TITLE"                 VARCHAR2(200 CHAR),
    "CREATED_AT"            TIMESTAMP(6),
    "CREATED_BY"            VARCHAR2(50 CHAR) NOT NULL ENABLE,
    "LAST_MODIFIED_AT"      TIMESTAMP(6),
    "LAST_MODIFIED_BY"      VARCHAR2(50 CHAR),
    "CODE"                  VARCHAR2(50 CHAR) NOT NULL ENABLE,
    "FULL_NAME"             VARCHAR2(100) NOT NULL ENABLE,
    "PHONE_NUMBER"          VARCHAR2(20 CHAR),
    "COMPLAINT_TYPE"        VARCHAR2(20 CHAR),
    "FEEDBACK"              VARCHAR2(2000 CHAR),
    "TICKET_ID"             VARCHAR2(36 CHAR),
    "COMPLAINT_TEMPLATE_ID" VARCHAR2(36 CHAR),
    PRIMARY KEY ("ID")
);

CREATE
INDEX "TICKET"."COMPLAINT_RECEIVED_USER_ID_IDX" ON
"TICKET"."COMPLAINT" ("RECEIVED_USER_ID");

CREATE
INDEX "TICKET"."COMPLAINT_CLOSED_USER_ID_IDX" ON
"TICKET"."COMPLAINT" ("CLOSED_USER_ID") ;

CREATE
INDEX "TICKET"."COMPLAINT_BUILDING_ID_IDX" ON
"TICKET"."COMPLAINT" ("BUILDING_ID");

CREATE
INDEX "TICKET"."COMPLAINT_FLOOR_ID_IDX" ON
"TICKET"."COMPLAINT" ("FLOOR_ID");

CREATE
INDEX "TICKET"."COMPLAINT_DELETED_IDX" ON
"TICKET"."COMPLAINT" ("DELETED");

CREATE
INDEX "TICKET"."COMPLAINT_CODE_IDX" ON
"TICKET"."COMPLAINT" ("CODE");

CREATE
INDEX "TICKET"."COMPLAINT_TICKET_ID_IDX" ON
"TICKET"."COMPLAINT" ("TICKET_ID");

CREATE TABLE "TICKET"."COMPLAINT_FILE"
(
    "ID"               VARCHAR2(36 CHAR) NOT NULL ENABLE,
    "COMPLAINT_ID"     VARCHAR2(36 CHAR),
    "DELETED"          NUMBER(1,0) NOT NULL ENABLE,
    "FILE_ID"          VARCHAR2(36 CHAR),
    "CREATED_AT"       TIMESTAMP(6),
    "CREATED_BY"       VARCHAR2(50 CHAR) NOT NULL ENABLE,
    "LAST_MODIFIED_AT" TIMESTAMP(6),
    "LAST_MODIFIED_BY" VARCHAR2(50 CHAR),
    PRIMARY KEY ("ID")
);

CREATE
INDEX "TICKET"."COMPLAINT_FILE_COMPLAINT_ID_IDX" ON
"TICKET"."COMPLAINT_FILE" ("COMPLAINT_ID");

CREATE
INDEX "TICKET"."COMPLAINT_FILE_FILE_ID_IDX" ON
"TICKET"."COMPLAINT_FILE" ("FILE_ID");

CREATE
INDEX "TICKET"."COMPLAINT_FILE_DELETED_IDX" ON
"TICKET"."COMPLAINT_FILE" ("DELETED");

CREATE TABLE "TICKET"."COMPLAINT_STATUS_HISTORY"
(
    "ID"               VARCHAR2(36 CHAR) NOT NULL ENABLE,
    "COMPLAINT_ID"     VARCHAR2(36 CHAR) NOT NULL ENABLE,
    "DELETED"          NUMBER(1,0) NOT NULL ENABLE,
    "STATUS"           VARCHAR2(20 CHAR) NOT NULL ENABLE,
    "USER_ID"          VARCHAR2(36 CHAR),
    "CREATED_AT"       TIMESTAMP(6),
    "CREATED_BY"       VARCHAR2(50 CHAR) NOT NULL ENABLE,
    "LAST_MODIFIED_AT" TIMESTAMP(6),
    "LAST_MODIFIED_BY" VARCHAR2(50 CHAR),
    "COMPLAINT_TYPE"   VARCHAR2(20 CHAR),
    PRIMARY KEY ("ID")
);

CREATE
INDEX "TICKET"."COMPLAINT_STATUS_HISTORY_COMPLAINT_ID_IDX" ON "TICKET"."COMPLAINT_STATUS_HISTORY" ("COMPLAINT_ID");
CREATE
INDEX "TICKET"."COMPLAINT_STATUS_HISTORY_USER_ID_IDX" ON "TICKET"."COMPLAINT_STATUS_HISTORY" ("USER_ID");
CREATE
INDEX "TICKET"."COMPLAINT_STATUS_HISTORY_DELETED_IDX" ON "TICKET"."COMPLAINT_STATUS_HISTORY" ("DELETED");