server:
  port: ${PORT:8586}

spring:
  datasource:
    url: ${POSTGRES_URI:jdbc:postgresql://192.168.2.105:5435/evo_meet?currentSchema=evo_meet&useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true}
    username: ${POSTGRES_USER:evo_meet}
    password: ${POSTGRES_PASSWORD:Evotek@1234}
    hikari:
      maximum-pool-size: ${CONNECTION_POOL_SIZE:32}
  redis:
    host: ${REDIS_HOST:192.168.2.105}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USER:evo.building.mb@gmail.com}
    password: ${MAIL_PASSWORD:123456aA@}
    protocol: ${MAIL_PROTOCOL:smtp}
    properties.mail.smtp:
      auth: true
      starttls.enable: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_URI:http://192.168.2.100:8061/api/certificate/.well-known/jwks.json}

eureka:
  instance:
    nonSecurePort: ${server.port}
    secure-port-enabled: false
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:192.168.2.100}:${EUREKA_PORT:8762}/eureka/

security:
  authentication:
    jwt:
      access-token-expires-in: 60m

app:
  domain: http://192.168.2.100:8800
  meeting:
    domain: ${PUBLIC_DOMAIN:http://192.168.2.100:8020}
