server:
  port: ${PORT:8084}

spring:
  datasource:
    url: ${ORACLE_URI:jdbc:}
    username: ${ORACLE_USER:}
    password: ${ORACLE_PASSWORD:}
    hikari:
      maximum-pool-size: ${CONNECTION_POOL_SIZE:32}
  redis:
    host: ${REDIS_HOST:}
    port: ${REDIS_PORT:}
    password: ${REDIS_PASSWORD:}
  rabbitmq:
    enabled: ${RABBITMQ_ENABLED:false}
    host: ${RABBITMQ_HOST:192.168.2.100}
    port: ${RABBITMQ_PORT:5671}
    username: ${RABBITMQ_USER:admin}
    password: ${RABBITMQ_PASSWORD:1qazXSW@3edc}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:mbamc}
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USER:evotraininghrm@gmail.com}
    password: ${MAIL_PASSWORD:123456aA@}
    protocol: ${MAIL_PROTOCOL:smtp}
    properties.mail.smtp:
      auth: true
      starttls.enable: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_URI:http://192.168.2.100:8011/api/certificate/.well-known/jwks.json}

eureka:
  instance:
    nonSecurePort: ${server.port}
    secure-port-enabled: false
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:192.168.2.100}:${EUREKA_PORT:8761}/eureka/

firebase:
  fcm-account-service-path: firebase/amc-fcm-prod.json

app:
  storage:
    folder_temporary: temporary
