#!/usr/bin/env groovy

node {
    stage('checkout') {
        checkout scm
    }

    stage('check java') {
        sh "java -version"
    }

    stage('clean') {
        sh "chmod +x mvnw"
        sh "./mvnw clean"
    }

    stage('test') {
        sh "./mvnw test"
    }

    stage('packaging') {
        sh "./mvnw verify -Pprod -DskipTests"
        archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
    }

    stage('deploy') {
        sh "kill \$(lsof -t -i:8511) > /dev/null 2> /dev/null || : "
        sh "cd ./target/ && /usr/lib/jvm/java-11-openjdk/bin/java -jar evo-iam-0.0.1-SNAPSHOT.jar --spring.profiles.active=dev"
    }
}
